apiVersion: v1
kind: Pod
metadata:
  name: sql-pod
  namespace: sql
  labels:
    app: mysql
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
    - name: sql-pod
      image: 135893829551.dkr.ecr.us-east-1.amazonaws.com/sql:v1.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
